name: Scan __builtin_mxc functions

on:
  # 18:00 UTC+8 = 10:00 UTC
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write          # needed only if the optional commit step is enabled

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # makes every `gh` call auto-authenticate

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4            # :contentReference[oaicite:0]{index=0}

      - name: Show gh version (debug)
        run: gh --version                    # GitHub CLI is pre-installed on ubuntu-latest :contentReference[oaicite:1]{index=1}

      - name: Fetch repository list
        run: |
          gh repo list MetaX-MACA --limit 1000 --json nameWithOwner \
            -q '.[].nameWithOwner' > repos.txt   # :contentReference[oaicite:2]{index=2}

      - name: Clone and scan repositories
        run: |
          mkdir -p results
          total=0
          while read repo; do
            echo "Scanning $repo"
            git clone --depth 1 "https://github.com/$repo.git"
            dir=$(basename "$repo")

            # unique symbols
            matches=$(grep -RhoE --exclude-dir='.git' \
              '__builtin_mxc[a-zA-Z0-9_]+' "$dir" | sort -u)
            count=$(echo "$matches" | wc -l)

            if [ "$count" -gt 0 ]; then
              {
                # repo title *is* the only link
                echo "### [$repo](https://github.com/$repo) (functions: $count)"
                echo
                # numbered list, no links
                echo "$matches" | nl -w2 -s'. '
                echo
              } >> results/body.md
              total=$((total + count))
            fi
            rm -rf "$dir"
          done < repos.txt
          echo "$total" > results/total.txt

      - name: Build report
        run: |
          grand_total=$(cat results/total.txt)
          {
            echo "# __builtin_mxc symbol report ($(date -u '+%Y-%m-%d %H:%M UTC'))"
            echo
            echo "**Total unique symbols across all repositories: ${grand_total}**"
            echo
            cat results/body.md || echo "_No matches found_"
          } > report.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4      # :contentReference[oaicite:3]{index=3}
        with:
          name: builtin-mxc-report
          path: report.md

      - name: Commit report to docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p docs
          mv report.md docs/builtin_mxc_report.md
          git add docs/builtin_mxc_report.md
          git commit -m "chore: update builtin_mxc report $(date -u '+%F')" || echo "Nothing to commit"
          git push
