name: Scan __builtin_mxc functions

on:
  schedule:
    - cron: '0 10 * * *'          # 18:00 UTC+8
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Fetch repository list
        run: |
          gh repo list MetaX-MACA --limit 1000 --json nameWithOwner \
            -q '.[].nameWithOwner' > repos.txt

      - name: Clone and scan repositories
        run: |
          mkdir -p results
          : > results/all_symbols.txt          # truncate / create
          total=0
          while read repo; do
            echo "Scanning $repo"
            git clone --depth 1 "https://github.com/$repo.git"
            dir=$(basename "$repo")

            matches=$(grep -RhoE --exclude-dir='.git' \
              '__builtin_mxc[a-zA-Z0-9_]+' "$dir" | sort -u || true)
            count=$(printf '%s\n' "$matches" | grep -c .)

            if [ "$count" -gt 0 ]; then
              {
                echo "### [$repo](https://github.com/$repo) (functions: $count)"
                echo
                printf '%s\n' "$matches" | nl -w2 -s'. '
                echo
              } >> results/body.md

              # add to global list (one per line)
              printf '%s\n' "$matches" >> results/all_symbols.txt
              total=$((total + count))
            fi
            rm -rf "$dir"
          done < repos.txt

          # build sorted-unique global list
          sort -u results/all_symbols.txt > results/unique_symbols.txt
          echo "$total" > results/total.txt

      - name: Build report
        run: |
          grand_total=$(cat results/total.txt)
          {
            echo "# __builtin_mxc symbol report ($(date -u '+%Y-%m-%d %H:%M UTC'))"
            echo
            echo "**Total unique symbols across all repositories: ${grand_total}**"
            echo
            # per-repo section
            cat results/body.md || echo "_No matches found_"
            echo
            # aggregated unique list
            echo "## Aggregated unique list"
            echo
            nl -w2 -s'. ' results/unique_symbols.txt
          } > report.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: builtin-mxc-report
          path: report.md

      - name: Commit report to docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p docs
          mv report.md docs/builtin_mxc_report.md
          git add docs/builtin_mxc_report.md
          git commit -m "chore: update builtin_mxc report $(date -u '+%F')" || echo "Nothing to commit"
          git push
